/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hibernate.tutorial.ui;

import com.hibernate.tutorial.mainclass.HibernateMain;
import com.hibernate.tutorial.ui.model.SertifTableModel;
import com.hibernate.tutorial.ui.model.SpisokVrachTableModel;
import com.hibernate.tutorial.ui.listener.JExampleMouseTableListener;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Талалаев
 */
public class MainFrame extends javax.swing.JFrame {

    HibernateMain hiber;
    private javax.swing.JTable tblSpisokVrach;
    private javax.swing.JTable tblSertif;
    private String[] args;
    /**
     * Creates new form MainFrame
     */
    
    
    public void init() {
    hiber = new HibernateMain();
        TableModel model1 = new SpisokVrachTableModel(hiber.getAllSpisokVrach());
        tblSpisokVrach = new JTable(model1);
        TableModel model2 = new SertifTableModel(hiber.getAll());
        tblSertif = new JTable(model2);
        

        tblSpisokVrach.setSize(new Dimension(900, 150));
        tblSertif.setSize(new Dimension(900, 150));
        
        
        tblSpisokVrach.addMouseListener(new JExampleMouseTableListener(this));

        Box contents = new Box(BoxLayout.Y_AXIS);
        contents.add(new JScrollPane(tblSpisokVrach));
        contents.add(new JScrollPane(tblSertif));

        this.getContentPane().add(contents);
        setPreferredSize(new Dimension(910, 700));
        this.pack();
        this.setDefaultLookAndFeelDecorated(true);
        this.setVisible(true);
    
    }
    
    public MainFrame() {
              
    }
    
    
    public void setArgs(String[] args) {
        this.args = args;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
